version: '3.8'

services:
  discovery-server:
    build: ./discovery-server
    image: discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - common

  api-gateway:
    build: ./api-gateway
    image: api-gateway
    container_name: api-gateway
    depends_on:
      - discovery-server
    ports:
      - "8086:8086"
    environment:
      - SPRING_APPLICATION_NAME=api-gateway
      - SPRING_PROFILES_ACTIVE=default
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-service:8888
    networks:
      - common

  authentication-service:
    build: ./authentication-service
    image: authentication-service
    container_name: authentication-service
    depends_on:
      - discovery-server
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=authentication-service
      - SPRING_PROFILES_ACTIVE=default
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
      - CONFIG_SERVER_URL=http://config-service:8888
      - spring.config.import=optional:configserver:http://config-service:8888


      - finance.mssql.db.jdbc=jdbc:sqlserver://104.247.162.242:55548
      - finance.mssql.db.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
      - finance.mssql.db.username=armanyay_root
      - finance.mssql.db.password=14ap_0L8q
      - finance.mssql.db.databaseName=armanyay_financemgmt
      - finance.mssql.db.trustSertificate=true

      # Hikari
      - finance.db.hikari.maxPoolSize=10
      - finance.db.hikari.minIdle=5
      - finance.db.hikari.idleTimeOut=30000
      - finance.db.hikari.connTimeout=20000
      - finance.db.hikari.maxLifeTime=180000

      # JWT
      - jwt.secret=9h5v8/AbGt3jPq4vM1uJlP6oE1lzkMZ+G9QcKlZq2g8=
      - jwt.expiration=86400
    networks:
      - common


  account-service:
    build: ./account-service
    image: account-service
    container_name: account-service
    depends_on:
      - discovery-server
    ports:
      - "8081:8081"
    environment:
      - SPRING_APPLICATION_NAME=account-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
      - CONFIG_SERVER_URL=http://config-service:8888
      - finance.mssql.db.jdbc=jdbc:sqlserver://104.247.162.242:55548
      - finance.mssql.db.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
      - finance.mssql.db.username=armanyay_root
      - finance.mssql.db.password=14ap_0L8q
      - finance.mssql.db.databaseName=armanyay_financemgmt
      - finance.mssql.db.trustSertificate=true
      - finance.db.hikari.maxPoolSize=10
      - finance.db.hikari.minIdle=5
      - finance.db.hikari.idleTimeOut=30000
      - finance.db.hikari.connTimeout=20000
      - finance.db.hikari.maxLifeTime=180000
      - jwt.secret=9h5v8/AbGt3jPq4vM1uJlP6oE1lzkMZ+G9QcKlZq2g8=
      - jwt.expiration=86400
    networks:
      - common

  currency-exchange-service:
    build: ./currency-exchange-service
    image: currency-exchange-service
    container_name: currency-exchange-service
    depends_on:
      - discovery-server
    ports:
      - "8083:8083"
    environment:
      - SPRING_APPLICATION_NAME=currency-exchange-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
      - CONFIG_SERVER_URL=http://config-service:8888
      - finance.mssql.db.jdbc=jdbc:sqlserver://104.247.162.242:55548
      - finance.mssql.db.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
      - finance.mssql.db.username=armanyay_root
      - finance.mssql.db.password=14ap_0L8q
      - finance.mssql.db.databaseName=armanyay_financemgmt
      - finance.mssql.db.trustSertificate=true
      - finance.db.hikari.maxPoolSize=10
      - finance.db.hikari.minIdle=5
      - finance.db.hikari.idleTimeOut=30000
      - finance.db.hikari.connTimeout=20000
      - finance.db.hikari.maxLifeTime=180000
      - jwt.secret=9h5v8/AbGt3jPq4vM1uJlP6oE1lzkMZ+G9QcKlZq2g8=
      - jwt.expiration=86400
    networks:
      - common

  user-service:
    build: ./user-service
    image: user-service
    container_name: user-service
    depends_on:
      - discovery-server
    ports:
      - "8084:8084"
    environment:
      - SPRING_APPLICATION_NAME=user-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
      - CONFIG_SERVER_URL=http://config-service:8888
      - finance.mssql.db.jdbc=jdbc:sqlserver://104.247.162.242:55548
      - finance.mssql.db.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
      - finance.mssql.db.username=armanyay_root
      - finance.mssql.db.password=14ap_0L8q
      - finance.mssql.db.databaseName=armanyay_financemgmt
      - finance.mssql.db.trustSertificate=true
      - finance.db.hikari.maxPoolSize=10
      - finance.db.hikari.minIdle=5
      - finance.db.hikari.idleTimeOut=30000
      - finance.db.hikari.connTimeout=20000
      - finance.db.hikari.maxLifeTime=180000
      - jwt.secret=9h5v8/AbGt3jPq4vM1uJlP6oE1lzkMZ+G9QcKlZq2g8=
      - jwt.expiration=86400
    networks:
      - common

  notification-service:
    build: ./notification-service
    image: notification-service
    container_name: notification-service
    depends_on:
      - discovery-server
    ports:
      - "8085:8085"
    environment:
      - SPRING_APPLICATION_NAME=notification-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
      - CONFIG_SERVER_URL=http://config-service:8888
      - finance.mssql.db.jdbc=jdbc:sqlserver://104.247.162.242:55548
      - finance.mssql.db.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
      - finance.mssql.db.username=armanyay_root
      - finance.mssql.db.password=14ap_0L8q
      - finance.mssql.db.databaseName=armanyay_financemgmt
      - finance.mssql.db.trustSertificate=true
      - finance.db.hikari.maxPoolSize=10
      - finance.db.hikari.minIdle=5
      - finance.db.hikari.idleTimeOut=30000
      - finance.db.hikari.connTimeout=20000
      - finance.db.hikari.maxLifeTime=180000
      - jwt.secret=9h5v8/AbGt3jPq4vM1uJlP6oE1lzkMZ+G9QcKlZq2g8=
      - jwt.expiration=86400
    networks:
      - common

  prometheus:
    image: prom/prometheus:v2.37.1
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "5000:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - authentication-service
      - user-service
      - notification-service
      - account-service
      - currency-exchange-service
    networks:
      - common

  grafana:
    image: grafana/grafana-oss:8.5.2
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    links:
      - prometheus:prometheus
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    networks:
      - common

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - common


networks:
  common:
    driver: bridge